### ISSUE TITLE
Section links with periods are broken

### ISSUE THREAD

**Issue by nglaeser** [troy/simpleoptout#11]
In the [table of contents](https://simpleoptout.com/#opt-out-of-data-sharing-by), links with periods are broken. For example,  "Amazon.com" links to `https://simpleoptout.com/#amazon.com` when it should link to `https://simpleoptout.com/#amazoncom` (notice the absence of a period between `amazon` and `com`).

**Comment by troy** [comment]
Thank you! I'll fix this and respond when it's live, probably over the weekend.

**Comment by troy** [comment]
Thanks, @nglaeser. This is fixed and live. If you encounter any other bugs or have suggestions, I'd welcome them.

**Comment by nglaeser** [comment]
Thanks! Looks like the period at the end of `#meredithtime-inc.` also needs to be removed :)

**Comment by troy** [comment]
Whoops, there's always one more. Fixed!
