### ISSUE TITLE
TruePeopleSearch

### ISSUE THREAD

**Issue by XtinaSchelin** [troy/simpleoptout#5]
Type: Reverse lookup entry
Policy is here: https://www.truepeoplesearch.com/privacy
Removal link is here: https://www.truepeoplesearch.com/removal

**Comment by troy** [comment]
@XtinaSchelin Thanks! I'll add it over the weekend and update this issue when it's live.

**Comment by troy** [comment]
@XtinaSchelin This is done and online: https://simpleoptout.com/#truepeoplesearch . Thanks!
