### ISSUE TITLE
Southwest Airlines

### ISSUE THREAD

**Issue by gavinr** [troy/simpleoptout#6]
https://t.iluv.southwest.com/webApp/swaAPP_DataPrivacy_OptOut

**Comment by troy** [comment]
Fantastic, thanks. I'll add it over the weekend and reply again here when it's live.

**Comment by gavinr** [comment]
You're welcome - thank you for maintaining this!

**Comment by troy** [comment]
My pleasure. This is live: https://simpleoptout.com/#southwest-airlines

In the process, I started exploring other airlines and found that United Airlines shares data with third parties ([details](https://simpleoptout.com/#united-airlines), doesn't seem to have a way to opt out of that sharing, and most severely, doesn't seem to comply with the CCPA "Do Not Sell" [requirements](https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=1798.135) ("sell" includes no-fee transfers). I just [asked United how CCPA subjects can opt out of data sharing](https://twitter.com/simpleoptout/status/1218335017824215040). Thank you for discovering this entire class of data sharing!
