### ISSUE TITLE
The opt out link for Twitter leads to an account that has been deactivated.

### ISSUE THREAD

**Issue by elireiner** [troy/simpleoptout#7]
Please update link for opt out text in Twitter table.

**Comment by troy** [comment]
Hi! Thanks for reporting this. I just tried all of the links in the Twitter part of the page (https://simpleoptout.com/#twitter) and they seem to go to the intended pages. It's possible that Twitter is serving you something different than it's serving me. Could you tell me which link you're clicking on, what URL you land on, and a screenshot or description of the page you're served?
