### ISSUE TITLE
eBay

### ISSUE THREAD

**Issue by AndrewBelt** [troy/simpleoptout#9]
https://www.ebay.com/adchoice

This only sets a local cookie and is not tied to your account. You need to opt out on all devices, and whenever the cookie expires (or after clearing cookies).

**Comment by troy** [comment]
@AndrewBelt thank you for taking the time to send this and for linking to the document 🙂

I read the eBay page and it looks like eBay honors opt-out cookies set by the Digital Advertising Alliance (DAA), which can be set on http://optout.aboutads.info/. Here's [a bit more](https://simpleoptout.com/#additions-and-updates) about it.

(You probably already run it, but for anyone else who reads this issue, I strongly recommend using uBlock Origin ([more](https://github.com/gorhill/uBlock#installation)). It won't prevent all on-site ads/sponsored listings, but it's much better than nothing.)

**Comment by AndrewBelt** [comment]
Oh you're right, it does. In that case, I'll close this since it's already covered.
